export const GET_ALL_TUTORIALS = "GET_ALL_TUTORIALS";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";

export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";